# PostgreSQL 部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: NAMESPACE_PLACEHOLDER
spec:
  replicas: 1 # 運行一個副本
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine # 使用指定版本的 PostgreSQL 映像
          envFrom:
            - secretRef:
                name: postgres-secret # 從 Secret 中載入環境變數
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # PostgreSQL 數據目錄
              name: postgres-storage
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "YOUR_DB_USER"] # 健康檢查命令
            initialDelaySeconds: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # 使用預定義的 PVC