# Kibana 部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1 # 運行一個副本
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:9.2.4 # 使用指定版本的 Kibana 映像
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200" # 連接到 Elasticsearch 服務
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: KIBANA_PASSWORD
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: KIBANA_ENCRYPTION_KEY
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: KIBANA_ENCRYPTION_KEY
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: KIBANA_ENCRYPTION_KEY
            - name: XPACK_FLEET_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-secret
                  key: KIBANA_ENCRYPTION_KEY
          ports:
            - containerPort: 5601 # Kibana 網頁介面端口